# A example of the configuration file for FS and Database
metadata:
  trial: "sharepoint_connector_testing"
  extra_class: "test2"
  url: !!expr Sys.getenv("SHAREPOINT_URL")

datasources:
  - name: "test"
    backend:
      type: "connector.sharepoint::connector_sharepoint"
      site_url: "{metadata.url}/{metadata.trial}"
      extra_class: "{metadata.extra_class}"
