metadata:
  trial: "0001"
  extra_class: "adam_connector"
  url: !!expr Sys.getenv("SHAREPOINT_SITE_URL")

datasources:
  - name: "adam"
    backend:
      type: "connector.sharepoint::connector_sharepoint"
      site_url: "{metadata.url}"
      folder: "{metadata.trial}/adam"
      extra_class: "{metadata.extra_class}"
  - name: "output"
    backend:
      type: "connector.sharepoint::connector_sharepoint"
      site_url: "{metadata.url}"
      folder: "{metadata.trial}/output"
